baseURL = "http://parulsancheti.co/"
languageCode = "en-in"
title = "My Awesome Static Site"
paginate = 10
# googleAnalytics = ""

[params]
    author = "Parul Sancheti"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "parulsancheti23"
    accent = "orange"
    showBorder = false
    backgroundColor = "red"
    font = "Lato" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["html","css"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/parulsancheti23/"
    name = "github"
    weight = 2


[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 3

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "stack-overflow"
    weight = 4
